version: "3.9"
services:
  keycloak:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=lizenz
      - KEYCLOAK_PASSWORD=lizenz
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=postgres
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
    depends_on:
      - postgres

  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres